/* Cloudflare Worker — turns a cart into a Stripe Checkout Session.
 *
 * The site is static, so it cannot hold a Stripe secret key or be trusted about
 * prices. The browser sends only product ids and quantities; every price is
 * looked up here, server side, from PRICES (generated by tools/build-static.py
 * from data.js). A tampered cart buys nothing at a tampered price.
 *
 * Deploy:
 *   1. Cloudflare dashboard → Workers & Pages → Create → paste this file
 *   2. Settings → Variables and Secrets → add secret STRIPE_SECRET_KEY
 *      (the sk_live_... value — it never appears in this repository)
 *   3. Copy the worker URL into SITE.checkoutEndpoint in assets/js/data.js
 */

import PRICES from "./prices.json";

const SITE = "https://picassointelligence.com";

/* Freight is charged once per order, not per line. Free above the threshold so
   large orders are not penalised for a cost that barely moves with weight. */
const SHIPPING_CENTS = 5000;
const FREE_SHIPPING_OVER_CENTS = 100000;

const CORS = {
  "Access-Control-Allow-Origin": SITE,
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...CORS },
  });
}

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") return new Response(null, { headers: CORS });
    if (request.method !== "POST") return json({ error: "POST only" }, 405);
    if (!env.STRIPE_SECRET_KEY) return json({ error: "Checkout is not configured." }, 500);

    let cart;
    try {
      cart = (await request.json()).lines;
    } catch {
      return json({ error: "Malformed request." }, 400);
    }
    if (!Array.isArray(cart) || !cart.length) return json({ error: "The cart is empty." }, 400);
    if (cart.length > 20) return json({ error: "Too many lines for one order." }, 400);

    const form = new URLSearchParams();
    let subtotal = 0;
    let i = 0;

    for (const line of cart) {
      const item = PRICES[line && line.id];
      /* An unknown id means the catalogue moved on since the cart was filled,
         or someone is probing. Either way, refuse rather than guess. */
      if (!item) return json({ error: "That model is no longer available: " + line.id }, 400);

      const qty = Math.floor(Number(line.qty));
      if (!Number.isFinite(qty) || qty < 1 || qty > 99) {
        return json({ error: "Quantity must be between 1 and 99." }, 400);
      }

      subtotal += item.cents * qty;
      form.set(`line_items[${i}][quantity]`, String(qty));
      form.set(`line_items[${i}][price_data][currency]`, "usd");
      form.set(`line_items[${i}][price_data][unit_amount]`, String(item.cents));
      form.set(`line_items[${i}][price_data][product_data][name]`, item.name);
      if (item.series) {
        form.set(`line_items[${i}][price_data][product_data][description]`, item.series);
      }
      i++;
    }

    const freight = subtotal >= FREE_SHIPPING_OVER_CENTS ? 0 : SHIPPING_CENTS;
    form.set("shipping_options[0][shipping_rate_data][type]", "fixed_amount");
    form.set("shipping_options[0][shipping_rate_data][fixed_amount][amount]", String(freight));
    form.set("shipping_options[0][shipping_rate_data][fixed_amount][currency]", "usd");
    form.set(
      "shipping_options[0][shipping_rate_data][display_name]",
      freight ? "Standard shipping" : "Shipping included"
    );

    form.set("mode", "payment");
    form.set("success_url", SITE + "/thank-you.html");
    form.set("cancel_url", SITE + "/cart.html");
    /* Physical goods: without an address there is nowhere to send them. */
    form.set("shipping_address_collection[allowed_countries][0]", "US");
    form.set("billing_address_collection", "required");
    form.set("phone_number_collection[enabled]", "true");
    form.set("automatic_tax[enabled]", "true");

    const res = await fetch("https://api.stripe.com/v1/checkout/sessions", {
      method: "POST",
      headers: {
        Authorization: "Bearer " + env.STRIPE_SECRET_KEY,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: form,
    });

    const data = await res.json();
    if (!res.ok) {
      /* Stripe's message can name internal detail, so log it and tell the
         customer something true and useful instead. */
      console.log("stripe error", JSON.stringify(data));
      return json({ error: "Stripe could not start this checkout. Please try again." }, 502);
    }
    return json({ url: data.url });
  },
};
