/* Cloudflare Worker — turns a cart into a Stripe Checkout Session, or a
 * PayPal order.
 *
 * The site is static, so it cannot hold a Stripe secret key or be trusted about
 * prices. The browser sends only product ids and quantities; every price is
 * looked up here, server side, from PRICES (generated by tools/build-static.py
 * from data.js). A tampered cart buys nothing at a tampered price.
 *
 * Deploy:
 *   1. Cloudflare dashboard → Workers & Pages → Create → paste
 *      worker/checkout.bundled.js, which has prices.json and zones.json inlined
 *   2. Settings → Variables and Secrets → add secret STRIPE_SECRET_KEY
 *      (the sk_live_... value — it never appears in this repository)
 *   3. Copy the worker URL into SITE.checkoutEndpoint in assets/js/data.js
 *
 * Tracking numbers: open the payment in the Dashboard and add metadata
 * `tracking`, and optionally `carrier` and `tracking_url`. That is what the
 * order lookup on the site reads; nothing else has to be kept in step.
 *
 * For PayPal (and Venmo, which rides on the same integration), also add
 * secrets PAYPAL_CLIENT_ID and PAYPAL_CLIENT_SECRET, and put the same client
 * id — it is public — in SITE.paypalClientId. Leave them unset and the PayPal
 * button simply never renders; Stripe is unaffected.
 */

import PRICES from "./prices.json";
import SHIPPING from "./shipping.json";

const SITE = "https://picassointelligence.com";

const ZONES = SHIPPING.zones;
/* The cart hides the pay button above this, but the button is not the
   control — a crafted request would sail past it. */
const SELF_SERVE_MAX_CENTS = SHIPPING.selfServeMax * 100;

/* Freight is charged once per order, not per line, and priced from the zone
   table in data.js — the same one the cart reads, so the total the customer
   was shown is the total charged. The browser picks a zone but cannot invent
   one, and the zone locks the countries Stripe will accept an address in, so
   choosing a cheap zone cannot buy delivery somewhere expensive. */
function freightCents(zone, subtotalCents) {
  for (const band of zone.rates) {
    if (band.upTo === null || subtotalCents < band.upTo * 100) return band.cost * 100;
  }
  return zone.rates[zone.rates.length - 1].cost * 100;
}

const CORS = {
  "Access-Control-Allow-Origin": SITE,
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

/* Rate limit.
 *
 * CORS is not a defence: it only constrains browsers, and a plain curl sails
 * straight past it. Nothing here risks money - every price is looked up server
 * side and the order ceiling is enforced below - but without a limit anyone can
 * loop on this endpoint and fill the Stripe dashboard with dead sessions, burn
 * the account's API quota and eat the free Workers allowance.
 *
 * The counter lives in the isolate, not in KV or a Durable Object, because those
 * need a binding configured by hand and this worker has to stay a single file
 * that gets pasted into the dashboard. The cost of that choice: the limit is per
 * isolate, so traffic spread across Cloudflare colos gets more headroom than the
 * number below suggests. It still stops what it is aimed at - one script
 * hammering from one machine, which lands in one colo.
 *
 * 12 a minute per IP per path is far above any human: a buyer clicks Checkout
 * once and retries twice at worst. A loop hits it in seconds.
 */
const RATE_WINDOW_MS = 60000;
const RATE_MAX = 12;
const hits = new Map();

function rateLimited(request, path) {
  /* Cloudflare always sets this. If it is somehow absent, allow the request:
     bucketing every unidentified caller together would throttle real buyers,
     and this guards against nuisance, not fraud. */
  const ip = request.headers.get("CF-Connecting-IP");
  if (!ip) return false;

  const now = Date.now();
  const cutoff = now - RATE_WINDOW_MS;
  const key = ip + " " + path;
  const recent = (hits.get(key) || []).filter((t) => t > cutoff);
  recent.push(now);
  hits.set(key, recent);

  /* A long-lived isolate would otherwise keep every IP it has ever seen. */
  if (hits.size > 5000) {
    for (const [k, times] of hits) {
      if (times[times.length - 1] <= cutoff) hits.delete(k);
    }
  }
  return recent.length > RATE_MAX;
}

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...CORS },
  });
}

const money = (cents) => (cents / 100).toFixed(2);
const usd = (cents) => ({ currency_code: "USD", value: money(cents) });

/* One reading of the cart for both processors. Returns either an error to send
   straight back, or the priced lines — so PayPal cannot be handed a total that
   Stripe would have refused. */
function priceCart(cart, zoneCode) {
  const zone = ZONES.find((z) => z.code === zoneCode) || ZONES[0];
  if (!Array.isArray(cart) || !cart.length) return { error: "The cart is empty." };
  if (cart.length > 20) return { error: "Too many lines for one order." };

  const lines = [];
  let subtotal = 0;
  for (const line of cart) {
    const item = PRICES[line && line.id];
    /* An unknown id means the catalogue moved on since the cart was filled,
       or someone is probing. Either way, refuse rather than guess. */
    if (!item) return { error: "That model is no longer available: " + line.id };
    const qty = Math.floor(Number(line.qty));
    if (!Number.isFinite(qty) || qty < 1 || qty > 99) {
      return { error: "Quantity must be between 1 and 99." };
    }
    subtotal += item.cents * qty;
    lines.push({ id: line.id, qty, item });
  }
  if (subtotal > SELF_SERVE_MAX_CENTS) {
    return {
      error: "Orders over $" + SHIPPING.selfServeMax.toLocaleString("en-US") +
        " are quoted rather than paid online. Send us the order and we will come " +
        "back with volume pricing.",
    };
  }
  return { zone, lines, subtotal, freight: freightCents(zone, subtotal) };
}

/* ---------- PayPal ------------------------------------------------------ */

const PAYPAL_API = "https://api-m.paypal.com";

async function paypalToken(env) {
  const auth = btoa(env.PAYPAL_CLIENT_ID + ":" + env.PAYPAL_CLIENT_SECRET);
  const res = await fetch(PAYPAL_API + "/v1/oauth2/token", {
    method: "POST",
    headers: {
      Authorization: "Basic " + auth,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: "grant_type=client_credentials",
  });
  const data = await res.json();
  if (!res.ok) throw new Error("paypal auth: " + JSON.stringify(data));
  return data.access_token;
}

async function paypal(env, path, method, body) {
  const token = await paypalToken(env);
  const res = await fetch(PAYPAL_API + path, {
    method,
    headers: { Authorization: "Bearer " + token, "Content-Type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  const data = text ? JSON.parse(text) : {};
  if (!res.ok) throw new Error("paypal " + path + ": " + text);
  return data;
}

/* Stripe Tax, used on its own. PayPal has no equivalent of Checkout's
   automatic_tax, and splitting tax records across two systems at filing time
   would be worse than one extra API call. Returns 0 wherever there is no
   registration, which is what the calculation itself returns. */
async function taxCents(env, priced, address) {
  if (!env.STRIPE_SECRET_KEY || !address) return 0;
  const form = new URLSearchParams();
  form.set("currency", "usd");
  priced.lines.forEach((l, i) => {
    form.set(`line_items[${i}][amount]`, String(l.item.cents * l.qty));
    form.set(`line_items[${i}][reference]`, l.id);
  });
  form.set("shipping_cost[amount]", String(priced.freight));
  const a = address;
  if (a.city) form.set("customer_details[address][city]", a.city);
  if (a.state) form.set("customer_details[address][state]", a.state);
  if (a.postalCode) form.set("customer_details[address][postal_code]", a.postalCode);
  form.set("customer_details[address][country]", a.countryCode || "US");
  form.set("customer_details[address_source]", "shipping");

  const res = await fetch("https://api.stripe.com/v1/tax/calculations", {
    method: "POST",
    headers: {
      Authorization: "Bearer " + env.STRIPE_SECRET_KEY,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: form,
  });
  const data = await res.json();
  /* A tax failure must not take the sale down with it: log it and charge no
     tax rather than refusing the order. */
  if (!res.ok) {
    console.log("tax calculation failed", JSON.stringify(data));
    return 0;
  }
  return data.tax_amount_exclusive || 0;
}

function paypalAmount(priced, tax) {
  return {
    ...usd(priced.subtotal + priced.freight + tax),
    breakdown: {
      item_total: usd(priced.subtotal),
      shipping: usd(priced.freight),
      tax_total: usd(tax),
    },
  };
}

export default {
  async fetch(request, env) {
    /* Preflight is legitimate and costs nothing, so it is not counted. */
    if (request.method === "OPTIONS") return new Response(null, { headers: CORS });
    if (request.method !== "POST") return json({ error: "POST only" }, 405);

    const path = new URL(request.url).pathname.replace(/\/+$/, "");

    /* Checked before the body is read, so a flood costs almost nothing. */
    if (rateLimited(request, path)) {
      return new Response(
        JSON.stringify({ error: "Too many requests. Wait a minute and try again." }),
        {
          status: 429,
          headers: {
            "Content-Type": "application/json",
            "Retry-After": String(RATE_WINDOW_MS / 1000),
            ...CORS,
          },
        }
      );
    }

    let payload;
    try {
      payload = await request.json();
    } catch {
      return json({ error: "Malformed request." }, 400);
    }

    try {
      if (path === "/order") return await orderStatus(payload, env);
      if (path === "/paypal/order") return await paypalOrder(payload, env);
      if (path === "/paypal/tax") return await paypalTax(payload, env);
      if (path === "/paypal/capture") return await paypalCapture(payload, env);
      return await stripeSession(payload, env);
    } catch (err) {
      /* A processor's own message can name internal detail, so log it and tell
         the customer something true and useful instead. */
      console.log("checkout error", path, String(err && err.message || err));
      return json({ error: "The payment provider could not be reached. Please try again." }, 502);
    }
  },
};

/* ---------- order reference and lookup ---------------------------------- */

/* Short enough to read down a phone and type back, from an alphabet with no
   O/0 or I/1 so it survives being read aloud. */
const REF_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

function orderRef() {
  let out = "";
  for (const b of crypto.getRandomValues(new Uint8Array(6))) {
    out += REF_ALPHABET[b % REF_ALPHABET.length];
  }
  return "PI-" + out;
}

async function stripeGet(env, path) {
  const res = await fetch("https://api.stripe.com/v1" + path, {
    headers: { Authorization: "Bearer " + env.STRIPE_SECRET_KEY },
  });
  const data = await res.json();
  if (!res.ok) throw new Error("stripe " + path + ": " + JSON.stringify(data));
  return data;
}

async function orderStatus(payload, env) {
  if (!env.STRIPE_SECRET_KEY) return json({ error: "Lookup is not configured." }, 500);
  const ref = String(payload.reference || "").trim().toUpperCase();
  const email = String(payload.email || "").trim().toLowerCase();
  if (!/^PI-[A-Z2-9]{6}$/.test(ref) || !email) {
    return json({ error: "Enter the order reference and the email you paid with." }, 400);
  }

  /* One message for "no such reference" and for "wrong email", so the form
     cannot be used to discover which references exist. */
  const no = () => json({ error: "No order matches that reference and email." }, 404);

  const q = encodeURIComponent('metadata["order"]:"' + ref + '"');
  const found = await stripeGet(env, "/payment_intents/search?limit=1&query=" + q);
  const hit = (found.data || [])[0];
  if (!hit) return no();

  const full = await stripeGet(env, "/payment_intents/" + hit.id + "?expand[]=latest_charge");
  const charge = full.latest_charge || {};
  const paidBy = [full.receipt_email, (charge.billing_details || {}).email]
    .filter(Boolean).map((e) => e.toLowerCase());
  if (!paidBy.includes(email)) return no();

  const meta = full.metadata || {};
  return json({
    reference: ref,
    placed: full.created,
    amount: money(full.amount),
    paid: full.status === "succeeded",
    refunded: Boolean(charge.refunded) || (charge.amount_refunded || 0) > 0,
    carrier: meta.carrier || "",
    tracking: meta.tracking || "",
    trackingUrl: meta.tracking_url || "",
  });
}

/* ---------- Stripe ------------------------------------------------------ */

async function stripeSession(payload, env) {
  if (!env.STRIPE_SECRET_KEY) return json({ error: "Checkout is not configured." }, 500);
  const priced = priceCart(payload.lines, payload.zone);
  if (priced.error) return json({ error: priced.error }, 400);
  const { zone, lines, freight } = priced;

  const form = new URLSearchParams();
  lines.forEach((l, i) => {
    form.set(`line_items[${i}][quantity]`, String(l.qty));
    form.set(`line_items[${i}][price_data][currency]`, "usd");
    form.set(`line_items[${i}][price_data][unit_amount]`, String(l.item.cents));
    form.set(`line_items[${i}][price_data][product_data][name]`, l.item.name);
    if (l.item.series) {
      form.set(`line_items[${i}][price_data][product_data][description]`, l.item.series);
    }
  });

  form.set("shipping_options[0][shipping_rate_data][type]", "fixed_amount");
  form.set("shipping_options[0][shipping_rate_data][fixed_amount][amount]", String(freight));
  form.set("shipping_options[0][shipping_rate_data][fixed_amount][currency]", "usd");
  form.set(
    "shipping_options[0][shipping_rate_data][display_name]",
    (freight ? "Standard shipping" : "Free shipping") +
      (zone.dutyPaid ? " — duty included" : " — duty on delivery")
  );

  form.set("mode", "payment");
  /* The same reference on the session and on the PaymentIntent: the session is
     what Checkout knows about, the PaymentIntent is what the lookup searches
     and what the Dashboard shows when a tracking number gets typed in. */
  const ref = orderRef();
  form.set("metadata[order]", ref);
  form.set("payment_intent_data[metadata][order]", ref);
  form.set("success_url", SITE + "/thank-you.html?o=" + ref);
  form.set("cancel_url", SITE + "/cart.html");
  /* Physical goods: without an address there is nowhere to send them. The list
     is the chosen zone's, so the address cannot land outside the area whose
     freight was just charged. */
  zone.countries.forEach((c, n) => {
    form.set(`shipping_address_collection[allowed_countries][${n}]`, c);
  });
  form.set("billing_address_collection", "required");
  form.set("phone_number_collection[enabled]", "true");
  form.set("automatic_tax[enabled]", "true");

  const res = await fetch("https://api.stripe.com/v1/checkout/sessions", {
    method: "POST",
    headers: {
      Authorization: "Bearer " + env.STRIPE_SECRET_KEY,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: form,
  });
  const data = await res.json();
  if (!res.ok) {
    console.log("stripe error", JSON.stringify(data));
    return json({ error: "Stripe could not start this checkout. Please try again." }, 502);
  }
  return json({ url: data.url });
}

/* ---------- PayPal ------------------------------------------------------ */

function paypalReady(env) {
  return Boolean(env.PAYPAL_CLIENT_ID && env.PAYPAL_CLIENT_SECRET);
}

async function paypalOrder(payload, env) {
  if (!paypalReady(env)) return json({ error: "PayPal is not configured." }, 500);
  const priced = priceCart(payload.lines, payload.zone);
  if (priced.error) return json({ error: priced.error }, 400);

  /* No address yet — the buyer chooses one inside PayPal, and /paypal/tax
     patches the total when they do. */
  const order = await paypal(env, "/v2/checkout/orders", "POST", {
    intent: "CAPTURE",
    purchase_units: [{
      reference_id: "default",
      amount: paypalAmount(priced, 0),
      items: priced.lines.map((l) => ({
        name: l.item.name.slice(0, 127),
        description: (l.item.series || "").slice(0, 127) || undefined,
        quantity: String(l.qty),
        unit_amount: usd(l.item.cents),
        category: "PHYSICAL_GOODS",
      })),
    }],
    payment_source: {
      paypal: {
        experience_context: {
          brand_name: "Picasso Intelligence",
          shipping_preference: "GET_FROM_FILE",
          user_action: "PAY_NOW",
          return_url: SITE + "/thank-you.html",
          cancel_url: SITE + "/cart.html",
        },
      },
    },
  });
  return json({ id: order.id });
}

/* Called when the buyer picks or changes an address inside PayPal. The order
   total is patched server side; the browser is told nothing it could forge. */
async function paypalTax(payload, env) {
  if (!paypalReady(env)) return json({ error: "PayPal is not configured." }, 500);
  const priced = priceCart(payload.lines, payload.zone);
  if (priced.error) return json({ error: priced.error }, 400);
  if (!payload.orderId) return json({ error: "Missing order." }, 400);

  const tax = await taxCents(env, priced, payload.address);
  await paypal(env, "/v2/checkout/orders/" + encodeURIComponent(payload.orderId), "PATCH", [{
    op: "replace",
    path: "/purchase_units/@reference_id=='default'/amount",
    value: paypalAmount(priced, tax),
  }]);
  return json({ tax: money(tax), total: money(priced.subtotal + priced.freight + tax) });
}

async function paypalCapture(payload, env) {
  if (!paypalReady(env)) return json({ error: "PayPal is not configured." }, 500);
  if (!payload.orderId) return json({ error: "Missing order." }, 400);
  const done = await paypal(
    env, "/v2/checkout/orders/" + encodeURIComponent(payload.orderId) + "/capture", "POST", {});
  const unit = (done.purchase_units || [])[0] || {};
  const capture = ((unit.payments || {}).captures || [])[0] || {};
  if (done.status !== "COMPLETED" && capture.status !== "COMPLETED") {
    console.log("paypal capture not completed", JSON.stringify(done));
    return json({ error: "PayPal did not complete the payment." }, 502);
  }
  return json({ ok: true, id: done.id });
}
