/* Cloudflare Worker — turns a cart into a Stripe Checkout Session, or a
 * PayPal order.
 *
 * The site is static, so it cannot hold a Stripe secret key or be trusted about
 * prices. The browser sends only product ids and quantities; every price is
 * looked up here, server side, from PRICES (generated by tools/build-static.py
 * from data.js). A tampered cart buys nothing at a tampered price.
 *
 * Deploy:
 *   1. Cloudflare dashboard → Workers & Pages → Create → paste
 *      worker/checkout.bundled.js, which has prices.json and zones.json inlined
 *   2. Settings → Variables and Secrets → add secret STRIPE_SECRET_KEY
 *      (the sk_live_... value — it never appears in this repository)
 *   3. Copy the worker URL into SITE.checkoutEndpoint in assets/js/data.js
 *
 * For PayPal (and Venmo, which rides on the same integration), also add
 * secrets PAYPAL_CLIENT_ID and PAYPAL_CLIENT_SECRET, and put the same client
 * id — it is public — in SITE.paypalClientId. Leave them unset and the PayPal
 * button simply never renders; Stripe is unaffected.
 */

import PRICES from "./prices.json";
import SHIPPING from "./shipping.json";

const SITE = "https://picassointelligence.com";

const ZONES = SHIPPING.zones;
/* The cart hides the pay button above this, but the button is not the
   control — a crafted request would sail past it. */
const SELF_SERVE_MAX_CENTS = SHIPPING.selfServeMax * 100;

/* Freight is charged once per order, not per line, and priced from the zone
   table in data.js — the same one the cart reads, so the total the customer
   was shown is the total charged. The browser picks a zone but cannot invent
   one, and the zone locks the countries Stripe will accept an address in, so
   choosing a cheap zone cannot buy delivery somewhere expensive. */
function freightCents(zone, subtotalCents) {
  for (const band of zone.rates) {
    if (band.upTo === null || subtotalCents < band.upTo * 100) return band.cost * 100;
  }
  return zone.rates[zone.rates.length - 1].cost * 100;
}

const CORS = {
  "Access-Control-Allow-Origin": SITE,
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...CORS },
  });
}

const money = (cents) => (cents / 100).toFixed(2);
const usd = (cents) => ({ currency_code: "USD", value: money(cents) });

/* One reading of the cart for both processors. Returns either an error to send
   straight back, or the priced lines — so PayPal cannot be handed a total that
   Stripe would have refused. */
function priceCart(cart, zoneCode) {
  const zone = ZONES.find((z) => z.code === zoneCode) || ZONES[0];
  if (!Array.isArray(cart) || !cart.length) return { error: "The cart is empty." };
  if (cart.length > 20) return { error: "Too many lines for one order." };

  const lines = [];
  let subtotal = 0;
  for (const line of cart) {
    const item = PRICES[line && line.id];
    /* An unknown id means the catalogue moved on since the cart was filled,
       or someone is probing. Either way, refuse rather than guess. */
    if (!item) return { error: "That model is no longer available: " + line.id };
    const qty = Math.floor(Number(line.qty));
    if (!Number.isFinite(qty) || qty < 1 || qty > 99) {
      return { error: "Quantity must be between 1 and 99." };
    }
    subtotal += item.cents * qty;
    lines.push({ id: line.id, qty, item });
  }
  if (subtotal > SELF_SERVE_MAX_CENTS) {
    return {
      error: "Orders over $" + SHIPPING.selfServeMax.toLocaleString("en-US") +
        " are quoted rather than paid online. Send us the order and we will come " +
        "back with volume pricing.",
    };
  }
  return { zone, lines, subtotal, freight: freightCents(zone, subtotal) };
}

/* ---------- PayPal ------------------------------------------------------ */

const PAYPAL_API = "https://api-m.paypal.com";

async function paypalToken(env) {
  const auth = btoa(env.PAYPAL_CLIENT_ID + ":" + env.PAYPAL_CLIENT_SECRET);
  const res = await fetch(PAYPAL_API + "/v1/oauth2/token", {
    method: "POST",
    headers: {
      Authorization: "Basic " + auth,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: "grant_type=client_credentials",
  });
  const data = await res.json();
  if (!res.ok) throw new Error("paypal auth: " + JSON.stringify(data));
  return data.access_token;
}

async function paypal(env, path, method, body) {
  const token = await paypalToken(env);
  const res = await fetch(PAYPAL_API + path, {
    method,
    headers: { Authorization: "Bearer " + token, "Content-Type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  const data = text ? JSON.parse(text) : {};
  if (!res.ok) throw new Error("paypal " + path + ": " + text);
  return data;
}

/* Stripe Tax, used on its own. PayPal has no equivalent of Checkout's
   automatic_tax, and splitting tax records across two systems at filing time
   would be worse than one extra API call. Returns 0 wherever there is no
   registration, which is what the calculation itself returns. */
async function taxCents(env, priced, address) {
  if (!env.STRIPE_SECRET_KEY || !address) return 0;
  const form = new URLSearchParams();
  form.set("currency", "usd");
  priced.lines.forEach((l, i) => {
    form.set(`line_items[${i}][amount]`, String(l.item.cents * l.qty));
    form.set(`line_items[${i}][reference]`, l.id);
  });
  form.set("shipping_cost[amount]", String(priced.freight));
  const a = address;
  if (a.city) form.set("customer_details[address][city]", a.city);
  if (a.state) form.set("customer_details[address][state]", a.state);
  if (a.postalCode) form.set("customer_details[address][postal_code]", a.postalCode);
  form.set("customer_details[address][country]", a.countryCode || "US");
  form.set("customer_details[address_source]", "shipping");

  const res = await fetch("https://api.stripe.com/v1/tax/calculations", {
    method: "POST",
    headers: {
      Authorization: "Bearer " + env.STRIPE_SECRET_KEY,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: form,
  });
  const data = await res.json();
  /* A tax failure must not take the sale down with it: log it and charge no
     tax rather than refusing the order. */
  if (!res.ok) {
    console.log("tax calculation failed", JSON.stringify(data));
    return 0;
  }
  return data.tax_amount_exclusive || 0;
}

function paypalAmount(priced, tax) {
  return {
    ...usd(priced.subtotal + priced.freight + tax),
    breakdown: {
      item_total: usd(priced.subtotal),
      shipping: usd(priced.freight),
      tax_total: usd(tax),
    },
  };
}

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") return new Response(null, { headers: CORS });
    if (request.method !== "POST") return json({ error: "POST only" }, 405);

    let payload;
    try {
      payload = await request.json();
    } catch {
      return json({ error: "Malformed request." }, 400);
    }

    const path = new URL(request.url).pathname.replace(/\/+$/, "");
    try {
      if (path === "/paypal/order") return await paypalOrder(payload, env);
      if (path === "/paypal/tax") return await paypalTax(payload, env);
      if (path === "/paypal/capture") return await paypalCapture(payload, env);
      return await stripeSession(payload, env);
    } catch (err) {
      /* A processor's own message can name internal detail, so log it and tell
         the customer something true and useful instead. */
      console.log("checkout error", path, String(err && err.message || err));
      return json({ error: "The payment provider could not be reached. Please try again." }, 502);
    }
  },
};

/* ---------- Stripe ------------------------------------------------------ */

async function stripeSession(payload, env) {
  if (!env.STRIPE_SECRET_KEY) return json({ error: "Checkout is not configured." }, 500);
  const priced = priceCart(payload.lines, payload.zone);
  if (priced.error) return json({ error: priced.error }, 400);
  const { zone, lines, freight } = priced;

  const form = new URLSearchParams();
  lines.forEach((l, i) => {
    form.set(`line_items[${i}][quantity]`, String(l.qty));
    form.set(`line_items[${i}][price_data][currency]`, "usd");
    form.set(`line_items[${i}][price_data][unit_amount]`, String(l.item.cents));
    form.set(`line_items[${i}][price_data][product_data][name]`, l.item.name);
    if (l.item.series) {
      form.set(`line_items[${i}][price_data][product_data][description]`, l.item.series);
    }
  });

  form.set("shipping_options[0][shipping_rate_data][type]", "fixed_amount");
  form.set("shipping_options[0][shipping_rate_data][fixed_amount][amount]", String(freight));
  form.set("shipping_options[0][shipping_rate_data][fixed_amount][currency]", "usd");
  form.set(
    "shipping_options[0][shipping_rate_data][display_name]",
    (freight ? "Standard shipping" : "Free shipping") +
      (zone.dutyPaid ? " — duty included" : " — duty on delivery")
  );

  form.set("mode", "payment");
  form.set("success_url", SITE + "/thank-you.html");
  form.set("cancel_url", SITE + "/cart.html");
  /* Physical goods: without an address there is nowhere to send them. The list
     is the chosen zone's, so the address cannot land outside the area whose
     freight was just charged. */
  zone.countries.forEach((c, n) => {
    form.set(`shipping_address_collection[allowed_countries][${n}]`, c);
  });
  form.set("billing_address_collection", "required");
  form.set("phone_number_collection[enabled]", "true");
  form.set("automatic_tax[enabled]", "true");

  const res = await fetch("https://api.stripe.com/v1/checkout/sessions", {
    method: "POST",
    headers: {
      Authorization: "Bearer " + env.STRIPE_SECRET_KEY,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: form,
  });
  const data = await res.json();
  if (!res.ok) {
    console.log("stripe error", JSON.stringify(data));
    return json({ error: "Stripe could not start this checkout. Please try again." }, 502);
  }
  return json({ url: data.url });
}

/* ---------- PayPal ------------------------------------------------------ */

function paypalReady(env) {
  return Boolean(env.PAYPAL_CLIENT_ID && env.PAYPAL_CLIENT_SECRET);
}

async function paypalOrder(payload, env) {
  if (!paypalReady(env)) return json({ error: "PayPal is not configured." }, 500);
  const priced = priceCart(payload.lines, payload.zone);
  if (priced.error) return json({ error: priced.error }, 400);

  /* No address yet — the buyer chooses one inside PayPal, and /paypal/tax
     patches the total when they do. */
  const order = await paypal(env, "/v2/checkout/orders", "POST", {
    intent: "CAPTURE",
    purchase_units: [{
      reference_id: "default",
      amount: paypalAmount(priced, 0),
      items: priced.lines.map((l) => ({
        name: l.item.name.slice(0, 127),
        description: (l.item.series || "").slice(0, 127) || undefined,
        quantity: String(l.qty),
        unit_amount: usd(l.item.cents),
        category: "PHYSICAL_GOODS",
      })),
    }],
    payment_source: {
      paypal: {
        experience_context: {
          brand_name: "Picasso Intelligence",
          shipping_preference: "GET_FROM_FILE",
          user_action: "PAY_NOW",
          return_url: SITE + "/thank-you.html",
          cancel_url: SITE + "/cart.html",
        },
      },
    },
  });
  return json({ id: order.id });
}

/* Called when the buyer picks or changes an address inside PayPal. The order
   total is patched server side; the browser is told nothing it could forge. */
async function paypalTax(payload, env) {
  if (!paypalReady(env)) return json({ error: "PayPal is not configured." }, 500);
  const priced = priceCart(payload.lines, payload.zone);
  if (priced.error) return json({ error: priced.error }, 400);
  if (!payload.orderId) return json({ error: "Missing order." }, 400);

  const tax = await taxCents(env, priced, payload.address);
  await paypal(env, "/v2/checkout/orders/" + encodeURIComponent(payload.orderId), "PATCH", [{
    op: "replace",
    path: "/purchase_units/@reference_id=='default'/amount",
    value: paypalAmount(priced, tax),
  }]);
  return json({ tax: money(tax), total: money(priced.subtotal + priced.freight + tax) });
}

async function paypalCapture(payload, env) {
  if (!paypalReady(env)) return json({ error: "PayPal is not configured." }, 500);
  if (!payload.orderId) return json({ error: "Missing order." }, 400);
  const done = await paypal(
    env, "/v2/checkout/orders/" + encodeURIComponent(payload.orderId) + "/capture", "POST", {});
  const unit = (done.purchase_units || [])[0] || {};
  const capture = ((unit.payments || {}).captures || [])[0] || {};
  if (done.status !== "COMPLETED" && capture.status !== "COMPLETED") {
    console.log("paypal capture not completed", JSON.stringify(done));
    return json({ error: "PayPal did not complete the payment." }, 502);
  }
  return json({ ok: true, id: done.id });
}
